### ISSUE TITLE
Benefiting from static analysis

### ISSUE THREAD

**Issue by szepeviktor** [postpromoterpro/post-promoter-pro#321]
Hello!
Is is necessary to make a minor modification for testing.

```php
//define( 'PPP_PATH', plugin_dir_path( __FILE__ ) );
define( 'PPP_PATH', __DIR__.'/' );
```

Add this to composer.json

```json
    "szepeviktor/phpstan-wordpress": "^0.1.0",
    "phpstan/phpstan-shim": "^0.11.0"
  },
  "minimum-stability": "dev",
  "config": {
    "optimize-autoloader": true
  },
  "autoload": {
    "psr-4": {
      "": "includes/"
    }
  }
```

phpstan.neon.dist

```yaml
# Start command: composer update && vendor/bin/phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    #level: max  Raise level!
    level: 2
    paths:
        - %currentWorkingDirectory%/post-promoter-pro.php
        - %currentWorkingDirectory%/includes/
    autoload_files:
        - %currentWorkingDirectory%/post-promoter-pro.php
        - %currentWorkingDirectory%/includes/filters.php
        - %currentWorkingDirectory%/includes/cron-functions.php
        - %currentWorkingDirectory%/includes/twitter-functions.php
        - %currentWorkingDirectory%/includes/linkedin-functions.php
        - %currentWorkingDirectory%/includes/pinterest-functions.php
        - %currentWorkingDirectory%/includes/facebook-functions.php
        - %currentWorkingDirectory%/includes/share-functions.php
        - %currentWorkingDirectory%/includes/wpme-functions.php
        - %currentWorkingDirectory%/includes/general-functions.php
        - %currentWorkingDirectory%/includes/bitly-functions.php
        - %currentWorkingDirectory%/includes/admin/actions.php
        - %currentWorkingDirectory%/includes/admin/admin-ajax.php
        - %currentWorkingDirectory%/includes/admin/admin-pages.php
        - %currentWorkingDirectory%/includes/admin/do-upgrades.php
        - %currentWorkingDirectory%/includes/admin/upgrades.php
        - %currentWorkingDirectory%/includes/admin/meta-boxes.php
    autoload_directories:
        - %currentWorkingDirectory%/includes/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with [34567] parameters, 2 required\.$#'
        - '#^Function do_action invoked with [3456] parameters, 1-2 required\.$#'
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```
